name: CI - Cloud Functions

on:
  pull_request:
    branches:
      - main
      - development*
    paths:
      - ".github/workflows/ci-cloud-functions.yaml"
      - "../../cloud/**"
  push:
    branches:
      - main
      - development
    paths:
      - ".github/workflows/ci-cloud-functions.yaml"
      - "../../cloud/**"


concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Tests
        uses: ./.github/actions/run-python-tests
        with:
          target: functions
