name: Shared Utils Package CI

on:
    pull_request:
        branches:
            - main
            - development*
        paths:
            - ".github/workflows/ci-package-shared-utils.yaml"
            - "packages/shared_utils/**"
    push:
        branches:
            - main
            - development
        paths:
            - ".github/workflows/ci-package-shared-utils.yaml"
            - "packages/shared_utils/**"


concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true
jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Run Tests
              uses: ./.github/actions/run-python-tests
              with:
                  target: shared_utils
